version: '3.8'

services:
  yongadb:
    image: postgres:15-alpine
    container_name: pts_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: yonga2026
      POSTGRES_DB: personel_takip_sistemi
    ports:
      - "5432:5432"
    volumes:
      - pts_db_data:/var/lib/postgresql/data
    networks:
      - pts_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pts_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - yongadb
    networks:
      - pts_network

networks:
  pts_network:
    driver: bridge

volumes:
  pts_db_data: